//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubeDownloader.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoutubeDownloader.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CANCEL ähnelt.
        /// </summary>
        public static string Download_Video_Button_Cancel {
            get {
                return ResourceManager.GetString("Download_Video_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DOWNLOAD ähnelt.
        /// </summary>
        public static string Download_Video_Button_Download {
            get {
                return ResourceManager.GetString("Download_Video_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format: ähnelt.
        /// </summary>
        public static string Download_Video_Format {
            get {
                return ResourceManager.GetString("Download_Video_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video quality: ähnelt.
        /// </summary>
        public static string Download_Video_Quality {
            get {
                return ResourceManager.GetString("Download_Video_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subtitles: ähnelt.
        /// </summary>
        public static string Download_Video_Subtitles {
            get {
                return ResourceManager.GetString("Download_Video_Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ACTIVATE ähnelt.
        /// </summary>
        public static string MessageBoxView_Button_Activate {
            get {
                return ResourceManager.GetString("MessageBoxView_Button_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CLOSE ähnelt.
        /// </summary>
        public static string MessageBoxView_Button_Close {
            get {
                return ResourceManager.GetString("MessageBoxView_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SAVE ähnelt.
        /// </summary>
        public static string MessageBoxView_Button_Save {
            get {
                return ResourceManager.GetString("MessageBoxView_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Name_Settings {
            get {
                return ResourceManager.GetString("Name_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel download ähnelt.
        /// </summary>
        public static string RootView_Button_Cancel_ToolTip {
            get {
                return ResourceManager.GetString("RootView_Button_Cancel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        public static string RootView_Button_OpenFile_ToolTip {
            get {
                return ResourceManager.GetString("RootView_Button_OpenFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process query (Enter) ähnelt.
        /// </summary>
        public static string RootView_Button_Query {
            get {
                return ResourceManager.GetString("RootView_Button_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart download ähnelt.
        /// </summary>
        public static string RootView_Button_Restart_ToolTip {
            get {
                return ResourceManager.GetString("RootView_Button_Restart_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Navigate to file ähnelt.
        /// </summary>
        public static string RootView_Button_ShowFile_ToolTip {
            get {
                return ResourceManager.GetString("RootView_Button_ShowFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy-paste URL or type in a search query to start downloading ähnelt.
        /// </summary>
        public static string RootView_ContentPlaceholder {
            get {
                return ResourceManager.GetString("RootView_ContentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove download ähnelt.
        /// </summary>
        public static string RootView_ContextMenu_RemoveDownload {
            get {
                return ResourceManager.GetString("RootView_ContextMenu_RemoveDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all inactive downloads ähnelt.
        /// </summary>
        public static string RootView_ContextMenu_RemoveInactiveDownloads {
            get {
                return ResourceManager.GetString("RootView_ContextMenu_RemoveInactiveDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all successful downloads ähnelt.
        /// </summary>
        public static string RootView_ContextMenu_RemoveSuccessfulDownloads {
            get {
                return ResourceManager.GetString("RootView_ContextMenu_RemoveSuccessfulDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart all failed downloads ähnelt.
        /// </summary>
        public static string RootView_ContextMenu_RestartFailedDownloads {
            get {
                return ResourceManager.GetString("RootView_ContextMenu_RestartFailedDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string RootView_FileName_Header {
            get {
                return ResourceManager.GetString("RootView_FileName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string RootView_Status {
            get {
                return ResourceManager.GetString("RootView_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ✗ Canceled ähnelt.
        /// </summary>
        public static string RootView_Status_Canceled {
            get {
                return ResourceManager.GetString("RootView_Status_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ✗ Failed ähnelt.
        /// </summary>
        public static string RootView_Status_Failed {
            get {
                return ResourceManager.GetString("RootView_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pending... ähnelt.
        /// </summary>
        public static string RootView_Status_Pending {
            get {
                return ResourceManager.GetString("RootView_Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ✓ Done ähnelt.
        /// </summary>
        public static string RootView_Status_Successful {
            get {
                return ResourceManager.GetString("RootView_Status_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL or search query (press Shift+Enter to add multiple) ähnelt.
        /// </summary>
        public static string RootView_TextBox_Query {
            get {
                return ResourceManager.GetString("RootView_TextBox_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Perform automatic updates on every launch ähnelt.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning: ähnelt.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_2 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die disabling this is NOT recommended because the application will stop working when integration with YouTube inevitably breaks in the future ähnelt.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_3 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-updates ähnelt.
        /// </summary>
        public static string SettingsView_AutoUpdates_Text {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use darker colors in the UI ähnelt.
        /// </summary>
        public static string SettingsView_DarkMode_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_DarkMode_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark mode ähnelt.
        /// </summary>
        public static string SettingsView_DarkMode_Text {
            get {
                return ResourceManager.GetString("SettingsView_DarkMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comma separated list of container formats excluded from format list when downloading a video ähnelt.
        /// </summary>
        public static string SettingsView_ExcludedContainer_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_ExcludedContainer_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ex: webm,ogg ähnelt.
        /// </summary>
        public static string SettingsView_ExcludedContainer_Desc_2 {
            get {
                return ResourceManager.GetString("SettingsView_ExcludedContainer_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excluded container formats ähnelt.
        /// </summary>
        public static string SettingsView_ExcludedContainer_Text {
            get {
                return ResourceManager.GetString("SettingsView_ExcludedContainer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template used for generating file names for downloaded videos ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available variables: ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_2 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - video&apos;s position in the list (if applicable) ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_3 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - video title ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_4 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - video author ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_5 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - video upload date ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_6 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - video length ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_7 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $num ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_Var_1 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_Var_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $title ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_Var_2 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_Var_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $author ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_Var_3 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_Var_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $uploadDate ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_Var_4 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_Var_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $length ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_Var_5 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_Var_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File name template ähnelt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Hint {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Media tags can be automatically inferred from video title and injected into output file ähnelt.
        /// </summary>
        public static string SettingsView_InjectTags_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_InjectTags_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically inject media tags ähnelt.
        /// </summary>
        public static string SettingsView_InjectTags_Text {
            get {
                return ResourceManager.GetString("SettingsView_InjectTags_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many downloads can be active at one time ähnelt.
        /// </summary>
        public static string SettingsView_MaxDownloads_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_MaxDownloads_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum concurrent downloads: ähnelt.
        /// </summary>
        public static string SettingsView_MaxDownloads_Text {
            get {
                return ResourceManager.GetString("SettingsView_MaxDownloads_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When selecting multiple videos to download, skip those that already have a matching file in the directory ähnelt.
        /// </summary>
        public static string SettingsView_SkipExistingFiles_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_SkipExistingFiles_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skip downloads for files that already exist ähnelt.
        /// </summary>
        public static string SettingsView_SkipExistingFiles_Text {
            get {
                return ResourceManager.GetString("SettingsView_SkipExistingFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a Token! ähnelt.
        /// </summary>
        public static string TokenVerifyView_Desc_1 {
            get {
                return ResourceManager.GetString("TokenVerifyView_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verify token ähnelt.
        /// </summary>
        public static string TokenVerifyView_Title {
            get {
                return ResourceManager.GetString("TokenVerifyView_Title", resourceCulture);
            }
        }
    }
}
