//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubeDownloader.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoutubeDownloader.Core.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Improved the accuracy of automatically resolved metadata. Also expanded the list of injected media tags to include some additional information.
        ///
        ///- Added `$id` file name template token. It resolves to the ID of the video.
        ///
        ///- Added auto-detection for dark mode. If your system is configured to prefer dark mode in applications, YoutubeDownloader will use it by default instead of light mode.
        ///
        ///- Removed the subtitle selection drop down shown when downloading videos. Subtitles are now downloaded automatica [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel download.
        /// </summary>
        public static string DashboardView_Cancel_ToolTip {
            get {
                return ResourceManager.GetString("DashboardView_Cancel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all downloads.
        /// </summary>
        public static string DashboardView_ContextMenu_Cancel_All_Downloads {
            get {
                return ResourceManager.GetString("DashboardView_ContextMenu_Cancel_All_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove inactive downloads.
        /// </summary>
        public static string DashboardView_ContextMenu_Remove_Inactive_Downloads {
            get {
                return ResourceManager.GetString("DashboardView_ContextMenu_Remove_Inactive_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove successful downloads.
        /// </summary>
        public static string DashboardView_ContextMenu_Remove_Successful_Downloads {
            get {
                return ResourceManager.GetString("DashboardView_ContextMenu_Remove_Successful_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart failed downloads.
        /// </summary>
        public static string DashboardView_ContextMenu_RestartFailedDownloads {
            get {
                return ResourceManager.GetString("DashboardView_ContextMenu_RestartFailedDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Query Text (Del).
        /// </summary>
        public static string DashboardView_Delete_Query {
            get {
                return ResourceManager.GetString("DashboardView_Delete_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string DashboardView_Download_File_Row_Title {
            get {
                return ResourceManager.GetString("DashboardView_Download_File_Row_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✗ Canceled.
        /// </summary>
        public static string DashboardView_Download_Status_Canceled {
            get {
                return ResourceManager.GetString("DashboardView_Download_Status_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Failed.
        /// </summary>
        public static string DashboardView_Download_Status_Failed {
            get {
                return ResourceManager.GetString("DashboardView_Download_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending....
        /// </summary>
        public static string DashboardView_Download_Status_Pending {
            get {
                return ResourceManager.GetString("DashboardView_Download_Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Done.
        /// </summary>
        public static string DashboardView_Download_Status_Successful {
            get {
                return ResourceManager.GetString("DashboardView_Download_Status_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any videos based on the query or URL you provided.
        /// </summary>
        public static string DashboardView_Nothing_Found_Message {
            get {
                return ResourceManager.GetString("DashboardView_Nothing_Found_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        public static string DashboardView_Nothing_Found_Title {
            get {
                return ResourceManager.GetString("DashboardView_Nothing_Found_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string DashboardView_OpenFile_ToolTip {
            get {
                return ResourceManager.GetString("DashboardView_OpenFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process query (Enter).
        /// </summary>
        public static string DashboardView_Query_Tooltip {
            get {
                return ResourceManager.GetString("DashboardView_Query_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart download.
        /// </summary>
        public static string DashboardView_Restart_ToolTip {
            get {
                return ResourceManager.GetString("DashboardView_Restart_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string DashboardView_Settings_Title {
            get {
                return ResourceManager.GetString("DashboardView_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show file.
        /// </summary>
        public static string DashboardView_ShowFile_ToolTip {
            get {
                return ResourceManager.GetString("DashboardView_ShowFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy-paste a.
        /// </summary>
        public static string DashboardView_TextBlock_Line_1 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or enter a.
        /// </summary>
        public static string DashboardView_TextBlock_Line_2 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search query.
        /// </summary>
        public static string DashboardView_TextBlock_Line_3 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to start downloading.
        /// </summary>
        public static string DashboardView_TextBlock_Line_4 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        public static string DashboardView_TextBlock_Line_5 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to add multiple items.
        /// </summary>
        public static string DashboardView_TextBlock_Line_6 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL or search query.
        /// </summary>
        public static string DashboardView_TextBox_Query {
            get {
                return ResourceManager.GetString("DashboardView_TextBox_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string Download_Video_Button_Cancel {
            get {
                return ResourceManager.GetString("Download_Video_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD.
        /// </summary>
        public static string Download_Video_Button_Download {
            get {
                return ResourceManager.GetString("Download_Video_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video quality:.
        /// </summary>
        public static string Download_Video_Quality {
            get {
                return ResourceManager.GetString("Download_Video_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on YouTube.
        /// </summary>
        public static string DownloadSingeSetupView_Open_link {
            get {
                return ResourceManager.GetString("DownloadSingeSetupView_Open_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License successfully activated!.
        /// </summary>
        public static string LicenseService_Activated_Description {
            get {
                return ResourceManager.GetString("LicenseService_Activated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated!.
        /// </summary>
        public static string LicenseService_Activated_Title {
            get {
                return ResourceManager.GetString("LicenseService_Activated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License already used!.
        /// </summary>
        public static string LicenseService_amount {
            get {
                return ResourceManager.GetString("LicenseService_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License disabled!.
        /// </summary>
        public static string LicenseService_disabled {
            get {
                return ResourceManager.GetString("LicenseService_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License expired! Please enter a new one!.
        /// </summary>
        public static string LicenseService_expired {
            get {
                return ResourceManager.GetString("LicenseService_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a vaild license!.
        /// </summary>
        public static string LicenseService_invalid {
            get {
                return ResourceManager.GetString("LicenseService_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection to the license server could not be established. Please try again!.
        /// </summary>
        public static string LicenseService_InvalidConnection {
            get {
                return ResourceManager.GetString("LicenseService_InvalidConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need a license to use the downloader!.
        /// </summary>
        public static string LicenseService_need_a_license {
            get {
                return ResourceManager.GetString("LicenseService_need_a_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVATE.
        /// </summary>
        public static string LicenseView_Activate {
            get {
                return ResourceManager.GetString("LicenseView_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string LicenseView_Title {
            get {
                return ResourceManager.GetString("LicenseView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        public static string MessageBoxView_Button_Close {
            get {
                return ResourceManager.GetString("MessageBoxView_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string MessageBoxView_Button_Save {
            get {
                return ResourceManager.GetString("MessageBoxView_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxView_Error {
            get {
                return ResourceManager.GetString("MessageBoxView_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string MessageBoxView_Search {
            get {
                return ResourceManager.GetString("MessageBoxView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update to % ....
        /// </summary>
        public static string RootViewModel_Update_Downloading {
            get {
                return ResourceManager.GetString("RootViewModel_Update_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform application update.
        /// </summary>
        public static string RootViewModel_Update_Error {
            get {
                return ResourceManager.GetString("RootViewModel_Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALL NOW.
        /// </summary>
        public static string RootViewModel_Update_Install {
            get {
                return ResourceManager.GetString("RootViewModel_Update_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update has been downloaded and will be installed when you exit.
        /// </summary>
        public static string RootViewModel_Update_Installable {
            get {
                return ResourceManager.GetString("RootViewModel_Update_Installable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to update server..
        /// </summary>
        public static string RootViewModel_Update_No_Connection {
            get {
                return ResourceManager.GetString("RootViewModel_Update_No_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $author.
        /// </summary>
        public static string SettingsService_FileNameTemplate_Author {
            get {
                return ResourceManager.GetString("SettingsService_FileNameTemplate_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $title.
        /// </summary>
        public static string SettingsService_FileNameTemplate_title {
            get {
                return ResourceManager.GetString("SettingsService_FileNameTemplate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $uploadDate.
        /// </summary>
        public static string SettingsService_FileNameTemplate_UploadDate {
            get {
                return ResourceManager.GetString("SettingsService_FileNameTemplate_UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform automatic updates on every launch.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning:.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_2 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabling this is NOT recommended because the application will stop working when integration with YouTube inevitably breaks in the future.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_3 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-updates.
        /// </summary>
        public static string SettingsView_AutoUpdates_Text {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use darker colors in the UI.
        /// </summary>
        public static string SettingsView_DarkMode_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_DarkMode_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string SettingsView_DarkMode_Text {
            get {
                return ResourceManager.GetString("SettingsView_DarkMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template used for generating file names for downloaded videos.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available tokens:.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_2 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - video&apos;s position in the list (if applicable).
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_3 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - video title.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_4 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - video author.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_5 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name template.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Hint {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many downloads can be active at one time.
        /// </summary>
        public static string SettingsView_MaxDownloads_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_MaxDownloads_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When selecting multiple videos to download, skip those that already have a matching file in the target directory.
        /// </summary>
        public static string SettingsView_SkipExistingFiles_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_SkipExistingFiles_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip existing files.
        /// </summary>
        public static string SettingsView_SkipExistingFiles_Text {
            get {
                return ResourceManager.GetString("SettingsView_SkipExistingFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable download option found..
        /// </summary>
        public static string VideoDownloader_No_Download {
            get {
                return ResourceManager.GetString("VideoDownloader_No_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest.
        /// </summary>
        public static string VideoDownloader_Quality_Highest {
            get {
                return ResourceManager.GetString("VideoDownloader_Quality_Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest.
        /// </summary>
        public static string VideoDownloader_Quality_Lowest {
            get {
                return ResourceManager.GetString("VideoDownloader_Quality_Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queries.
        /// </summary>
        public static string VideoDownloader_Query_Count {
            get {
                return ResourceManager.GetString("VideoDownloader_Query_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown video quality preference.
        /// </summary>
        public static string VideoDownloader_Unkown_Quality {
            get {
                return ResourceManager.GetString("VideoDownloader_Unkown_Quality", resourceCulture);
            }
        }
    }
}
