//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubeDownloader.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoutubeDownloader.Core.Language.Resources.de", typeof(Resources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        public static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download abbrechen.
        /// </summary>
        public static string DashboardView_Cancel_ToolTip {
            get {
                return ResourceManager.GetString("DashboardView_Cancel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Downloads abbrechen.
        /// </summary>
        public static string DashboardView_ContextMenu_Cancel_All_Downloads {
            get {
                return ResourceManager.GetString("DashboardView_ContextMenu_Cancel_All_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaktiven Downloads entfernen.
        /// </summary>
        public static string DashboardView_ContextMenu_Remove_Inactive_Downloads {
            get {
                return ResourceManager.GetString("DashboardView_ContextMenu_Remove_Inactive_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreiche Downloads entfernen.
        /// </summary>
        public static string DashboardView_ContextMenu_Remove_Successful_Downloads {
            get {
                return ResourceManager.GetString("DashboardView_ContextMenu_Remove_Successful_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlgeschlagene Downloads neustarten.
        /// </summary>
        public static string DashboardView_ContextMenu_RestartFailedDownloads {
            get {
                return ResourceManager.GetString("DashboardView_ContextMenu_RestartFailedDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche löschen (Entf).
        /// </summary>
        public static string DashboardView_Delete_Query {
            get {
                return ResourceManager.GetString("DashboardView_Delete_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        public static string DashboardView_Download_File_Row_Title {
            get {
                return ResourceManager.GetString("DashboardView_Download_File_Row_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✗ Abbgeborchen.
        /// </summary>
        public static string DashboardView_Download_Status_Canceled {
            get {
                return ResourceManager.GetString("DashboardView_Download_Status_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Fehlgeschlagen.
        /// </summary>
        public static string DashboardView_Download_Status_Failed {
            get {
                return ResourceManager.GetString("DashboardView_Download_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausstehend....
        /// </summary>
        public static string DashboardView_Download_Status_Pending {
            get {
                return ResourceManager.GetString("DashboardView_Download_Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Fertig.
        /// </summary>
        public static string DashboardView_Download_Status_Successful {
            get {
                return ResourceManager.GetString("DashboardView_Download_Status_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basierend auf dem Suchbegriff oder der URL konnten keine Videos gefunden werden.
        /// </summary>
        public static string DashboardView_Nothing_Found_Message {
            get {
                return ResourceManager.GetString("DashboardView_Nothing_Found_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nichts gefunden.
        /// </summary>
        public static string DashboardView_Nothing_Found_Title {
            get {
                return ResourceManager.GetString("DashboardView_Nothing_Found_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abspielen.
        /// </summary>
        public static string DashboardView_OpenFile_ToolTip {
            get {
                return ResourceManager.GetString("DashboardView_OpenFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen (Enter).
        /// </summary>
        public static string DashboardView_Query_Tooltip {
            get {
                return ResourceManager.GetString("DashboardView_Query_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download neustarten.
        /// </summary>
        public static string DashboardView_Restart_ToolTip {
            get {
                return ResourceManager.GetString("DashboardView_Restart_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string DashboardView_Settings_Title {
            get {
                return ResourceManager.GetString("DashboardView_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Datei.
        /// </summary>
        public static string DashboardView_ShowFile_ToolTip {
            get {
                return ResourceManager.GetString("DashboardView_ShowFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy-paste eine.
        /// </summary>
        public static string DashboardView_TextBlock_Line_1 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oder gebe einen.
        /// </summary>
        public static string DashboardView_TextBlock_Line_2 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchbegriff.
        /// </summary>
        public static string DashboardView_TextBlock_Line_3 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an um Videos herunterzuladen.
        /// </summary>
        public static string DashboardView_TextBlock_Line_4 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drücke.
        /// </summary>
        public static string DashboardView_TextBlock_Line_5 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to um mehrere Elemente hinzuzufügen.
        /// </summary>
        public static string DashboardView_TextBlock_Line_6 {
            get {
                return ResourceManager.GetString("DashboardView_TextBlock_Line_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL oder Suchbegriff.
        /// </summary>
        public static string DashboardView_TextBox_Query {
            get {
                return ResourceManager.GetString("DashboardView_TextBox_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABBRECHEN.
        /// </summary>
        public static string Download_Video_Button_Cancel {
            get {
                return ResourceManager.GetString("Download_Video_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HERUNTERLADEN.
        /// </summary>
        public static string Download_Video_Button_Download {
            get {
                return ResourceManager.GetString("Download_Video_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videoqualität:.
        /// </summary>
        public static string Download_Video_Quality {
            get {
                return ResourceManager.GetString("Download_Video_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf YouTube öffnen.
        /// </summary>
        public static string DownloadSingeSetupView_Open_link {
            get {
                return ResourceManager.GetString("DownloadSingeSetupView_Open_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lizenzschlüssel erfolgreich aktiviert!.
        /// </summary>
        public static string LicenseService_Activated_Description {
            get {
                return ResourceManager.GetString("LicenseService_Activated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiviert!.
        /// </summary>
        public static string LicenseService_Activated_Title {
            get {
                return ResourceManager.GetString("LicenseService_Activated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Lizenz wurde bereits eingelöst!.
        /// </summary>
        public static string LicenseService_amount {
            get {
                return ResourceManager.GetString("LicenseService_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesee Lizenz wurde deaktiviert!.
        /// </summary>
        public static string LicenseService_disabled {
            get {
                return ResourceManager.GetString("LicenseService_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Lizenz ist abgelaufen! Bitte aktivieren eine neue!.
        /// </summary>
        public static string LicenseService_expired {
            get {
                return ResourceManager.GetString("LicenseService_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib eine gültige Lizenz an!.
        /// </summary>
        public static string LicenseService_invalid {
            get {
                return ResourceManager.GetString("LicenseService_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Verbindung zum Lizenzserver hergestellt werden. Bitte versuche es erneut!.
        /// </summary>
        public static string LicenseService_InvalidConnection {
            get {
                return ResourceManager.GetString("LicenseService_InvalidConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um den Downloader zu verwenden benötigst du einen Lizenzschlüssel!.
        /// </summary>
        public static string LicenseService_need_a_license {
            get {
                return ResourceManager.GetString("LicenseService_need_a_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKTIVIEREN.
        /// </summary>
        public static string LicenseView_Activate {
            get {
                return ResourceManager.GetString("LicenseView_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrierung.
        /// </summary>
        public static string LicenseView_Title {
            get {
                return ResourceManager.GetString("LicenseView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHLIEßEN.
        /// </summary>
        public static string MessageBoxView_Button_Close {
            get {
                return ResourceManager.GetString("MessageBoxView_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEICHERN.
        /// </summary>
        public static string MessageBoxView_Button_Save {
            get {
                return ResourceManager.GetString("MessageBoxView_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string MessageBoxView_Error {
            get {
                return ResourceManager.GetString("MessageBoxView_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche:.
        /// </summary>
        public static string MessageBoxView_Search {
            get {
                return ResourceManager.GetString("MessageBoxView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update von % herunterladen....
        /// </summary>
        public static string RootViewModel_Update_Downloading {
            get {
                return ResourceManager.GetString("RootViewModel_Update_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualiserung fehlgeschlagen.
        /// </summary>
        public static string RootViewModel_Update_Error {
            get {
                return ResourceManager.GetString("RootViewModel_Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JETZT INSTALLIEREN.
        /// </summary>
        public static string RootViewModel_Update_Install {
            get {
                return ResourceManager.GetString("RootViewModel_Update_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Update wurde heruntergeladen und wird beim Beenden installiert.
        /// </summary>
        public static string RootViewModel_Update_Installable {
            get {
                return ResourceManager.GetString("RootViewModel_Update_Installable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Verbindung zum Updateserver hergestellt werden..
        /// </summary>
        public static string RootViewModel_Update_No_Connection {
            get {
                return ResourceManager.GetString("RootViewModel_Update_No_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $autor.
        /// </summary>
        public static string SettingsService_FileNameTemplate_Author {
            get {
                return ResourceManager.GetString("SettingsService_FileNameTemplate_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $titel.
        /// </summary>
        public static string SettingsService_FileNameTemplate_title {
            get {
                return ResourceManager.GetString("SettingsService_FileNameTemplate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $datum.
        /// </summary>
        public static string SettingsService_FileNameTemplate_UploadDate {
            get {
                return ResourceManager.GetString("SettingsService_FileNameTemplate_UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatische Updates nach jedem Start.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung:.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_2 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Funktion zu deaktivieren ist NICHT empfohlen, da der Downloader bei neunen Änderungen von Youtube möglicherweise nicht mehr funktioniert.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_3 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatische Updates.
        /// </summary>
        public static string SettingsView_AutoUpdates_Text {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunkle Farben im Interface verwenden.
        /// </summary>
        public static string SettingsView_DarkMode_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_DarkMode_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunkles Design.
        /// </summary>
        public static string SettingsView_DarkMode_Text {
            get {
                return ResourceManager.GetString("SettingsView_DarkMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Vorlage wird zur Generierung des Dateinamen der Downloads benutzt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mögliche tokens:.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_2 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Position des Videos in einer Playlist (falls vorhanden).
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_3 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Videotitel.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_4 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Videoautor.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_5 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateinamenvorlage.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Hint {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der gleichzeitig aktiven Downloads.
        /// </summary>
        public static string SettingsView_MaxDownloads_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_MaxDownloads_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überspringe bei mehreren Videodownloads bereits exsitente Datein im Zielverzeichnis.
        /// </summary>
        public static string SettingsView_SkipExistingFiles_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_SkipExistingFiles_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorhandene Downloads überspringen.
        /// </summary>
        public static string SettingsView_SkipExistingFiles_Text {
            get {
                return ResourceManager.GetString("SettingsView_SkipExistingFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine passende Download-Option gefunden..
        /// </summary>
        public static string VideoDownloader_No_Download {
            get {
                return ResourceManager.GetString("VideoDownloader_No_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höchste.
        /// </summary>
        public static string VideoDownloader_Quality_Highest {
            get {
                return ResourceManager.GetString("VideoDownloader_Quality_Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niedrigste.
        /// </summary>
        public static string VideoDownloader_Quality_Lowest {
            get {
                return ResourceManager.GetString("VideoDownloader_Quality_Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ergebnisse.
        /// </summary>
        public static string VideoDownloader_Query_Count {
            get {
                return ResourceManager.GetString("VideoDownloader_Query_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannte bevorzugte Videoqualität.
        /// </summary>
        public static string VideoDownloader_Unkown_Quality {
            get {
                return ResourceManager.GetString("VideoDownloader_Unkown_Quality", resourceCulture);
            }
        }
    }
}
