//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubeDownloader.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoutubeDownloader.Core.Language.Resources.de", typeof(Resources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        public static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nichts gefunden.
        /// </summary>
        public static string Download_Nothing_Found_1 {
            get {
                return ResourceManager.GetString("Download_Nothing_Found_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basierend auf dem angegebenen Suchbegriff oder der URL konnten keine Videos gefunden werden.
        /// </summary>
        public static string Download_Nothing_Found_2 {
            get {
                return ResourceManager.GetString("Download_Nothing_Found_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Video % enthält keine Streams.
        /// </summary>
        public static string Download_Nothing_Found_3 {
            get {
                return ResourceManager.GetString("Download_Nothing_Found_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABBRECHEN.
        /// </summary>
        public static string Download_Video_Button_Cancel {
            get {
                return ResourceManager.GetString("Download_Video_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HERUNTERLADEN.
        /// </summary>
        public static string Download_Video_Button_Download {
            get {
                return ResourceManager.GetString("Download_Video_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string Download_Video_Format {
            get {
                return ResourceManager.GetString("Download_Video_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videoqualität:.
        /// </summary>
        public static string Download_Video_Quality {
            get {
                return ResourceManager.GetString("Download_Video_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untertitel:.
        /// </summary>
        public static string Download_Video_Subtitles {
            get {
                return ResourceManager.GetString("Download_Video_Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Lizenzschlüssel wurde erfolgreich aktiviert!.
        /// </summary>
        public static string LicenseService_Activated_Description {
            get {
                return ResourceManager.GetString("LicenseService_Activated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiviert!.
        /// </summary>
        public static string LicenseService_Activated_Title {
            get {
                return ResourceManager.GetString("LicenseService_Activated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Lizenz wurde bereits eingelöst!.
        /// </summary>
        public static string LicenseService_amount {
            get {
                return ResourceManager.GetString("LicenseService_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Token wurde deaktiviert!.
        /// </summary>
        public static string LicenseService_disabled {
            get {
                return ResourceManager.GetString("LicenseService_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Token ist abgelaufen! Bitte aktivieren Sie einen neuen!.
        /// </summary>
        public static string LicenseService_expired {
            get {
                return ResourceManager.GetString("LicenseService_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte benutze einen gültigen Token!.
        /// </summary>
        public static string LicenseService_invalid {
            get {
                return ResourceManager.GetString("LicenseService_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Verbindung zum Lizenzserver hergestellt werden. Bitte versuche es erneut!.
        /// </summary>
        public static string LicenseService_InvalidConnection {
            get {
                return ResourceManager.GetString("LicenseService_InvalidConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um den Downloader zu verwenden benötigst du einen Lizenzschlüssel!.
        /// </summary>
        public static string LicenseService_need_a_token {
            get {
                return ResourceManager.GetString("LicenseService_need_a_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKTIVIEREN.
        /// </summary>
        public static string MessageBoxView_Button_Activate {
            get {
                return ResourceManager.GetString("MessageBoxView_Button_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHLIEßEN.
        /// </summary>
        public static string MessageBoxView_Button_Close {
            get {
                return ResourceManager.GetString("MessageBoxView_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEICHERN.
        /// </summary>
        public static string MessageBoxView_Button_Save {
            get {
                return ResourceManager.GetString("MessageBoxView_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string MessageBoxView_Error {
            get {
                return ResourceManager.GetString("MessageBoxView_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnten keine Ergebnisse für % gefunden werden.
        /// </summary>
        public static string MessageBoxView_Not_Found {
            get {
                return ResourceManager.GetString("MessageBoxView_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche:.
        /// </summary>
        public static string MessageBoxView_Search {
            get {
                return ResourceManager.GetString("MessageBoxView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehrfachauswahl.
        /// </summary>
        public static string MultipleDownloads_Text {
            get {
                return ResourceManager.GetString("MultipleDownloads_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string Name_Settings {
            get {
                return ResourceManager.GetString("Name_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download abbrechen.
        /// </summary>
        public static string RootView_Button_Cancel_ToolTip {
            get {
                return ResourceManager.GetString("RootView_Button_Cancel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche löschen (Entf).
        /// </summary>
        public static string RootView_Button_Delete_Query {
            get {
                return ResourceManager.GetString("RootView_Button_Delete_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abspielen.
        /// </summary>
        public static string RootView_Button_OpenFile_ToolTip {
            get {
                return ResourceManager.GetString("RootView_Button_OpenFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen (Enter).
        /// </summary>
        public static string RootView_Button_Query {
            get {
                return ResourceManager.GetString("RootView_Button_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download neustarten.
        /// </summary>
        public static string RootView_Button_Restart_ToolTip {
            get {
                return ResourceManager.GetString("RootView_Button_Restart_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zu Datei navigieren.
        /// </summary>
        public static string RootView_Button_ShowFile_ToolTip {
            get {
                return ResourceManager.GetString("RootView_Button_ShowFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL oder einen Suchbegriff eingeben um den Download zu starten.
        /// </summary>
        public static string RootView_ContentPlaceholder {
            get {
                return ResourceManager.GetString("RootView_ContentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download entfernen.
        /// </summary>
        public static string RootView_ContextMenu_RemoveDownload {
            get {
                return ResourceManager.GetString("RootView_ContextMenu_RemoveDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle inaktiven Downloads entfernen.
        /// </summary>
        public static string RootView_ContextMenu_RemoveInactiveDownloads {
            get {
                return ResourceManager.GetString("RootView_ContextMenu_RemoveInactiveDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle erfolgreichen Downloads entfernen.
        /// </summary>
        public static string RootView_ContextMenu_RemoveSuccessfulDownloads {
            get {
                return ResourceManager.GetString("RootView_ContextMenu_RemoveSuccessfulDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle fehlgeschlagenen Downloads neustarten.
        /// </summary>
        public static string RootView_ContextMenu_RestartFailedDownloads {
            get {
                return ResourceManager.GetString("RootView_ContextMenu_RestartFailedDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        public static string RootView_FileName_Header {
            get {
                return ResourceManager.GetString("RootView_FileName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RootView_Status {
            get {
                return ResourceManager.GetString("RootView_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✗ Abbgeborchen.
        /// </summary>
        public static string RootView_Status_Canceled {
            get {
                return ResourceManager.GetString("RootView_Status_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✗ Fehlgeschlagen.
        /// </summary>
        public static string RootView_Status_Failed {
            get {
                return ResourceManager.GetString("RootView_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warten....
        /// </summary>
        public static string RootView_Status_Pending {
            get {
                return ResourceManager.GetString("RootView_Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Fertig.
        /// </summary>
        public static string RootView_Status_Successful {
            get {
                return ResourceManager.GetString("RootView_Status_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL oder Suchen (Shift+Enter für Zeilenumbruch).
        /// </summary>
        public static string RootView_TextBox_Query {
            get {
                return ResourceManager.GetString("RootView_TextBox_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $autor.
        /// </summary>
        public static string SettingsService_FileNameTemplate_Author {
            get {
                return ResourceManager.GetString("SettingsService_FileNameTemplate_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $id.
        /// </summary>
        public static string SettingsService_FileNameTemplate_Id {
            get {
                return ResourceManager.GetString("SettingsService_FileNameTemplate_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $nummer.
        /// </summary>
        public static string SettingsService_FileNameTemplate_Num {
            get {
                return ResourceManager.GetString("SettingsService_FileNameTemplate_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $datum.
        /// </summary>
        public static string SettingsService_FileNameTemplate_UploadDate {
            get {
                return ResourceManager.GetString("SettingsService_FileNameTemplate_UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkennt und trägt automatisch Youtube-formatierte Links aus der Zwischenablage in die Suchleiste ein.
        /// </summary>
        public static string SettingsView_AutoImportClipboard_Desc {
            get {
                return ResourceManager.GetString("SettingsView_AutoImportClipboard_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwischenablage automatisch einfügen.
        /// </summary>
        public static string SettingsView_AutoImportClipboard_Text {
            get {
                return ResourceManager.GetString("SettingsView_AutoImportClipboard_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Führt automatische Updates nach jedem Start durch.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung:.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_2 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Funktion zu deaktivieren ist NICHT empfohlen, da der Downloader bei neunen Änderungen von Youtube möglicherweise nicht mehr funktioniert.
        /// </summary>
        public static string SettingsView_AutoUpdates_Desc_3 {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatische Updates.
        /// </summary>
        public static string SettingsView_AutoUpdates_Text {
            get {
                return ResourceManager.GetString("SettingsView_AutoUpdates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzt dunkle Farben im Interface.
        /// </summary>
        public static string SettingsView_DarkMode_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_DarkMode_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunkles Design.
        /// </summary>
        public static string SettingsView_DarkMode_Text {
            get {
                return ResourceManager.GetString("SettingsView_DarkMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine durch Kommas getrennte Liste der Formate, die beim Herunterladen eines Videos von der Formatliste ausgeschlossen wird.
        /// </summary>
        public static string SettingsView_ExcludedContainer_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_ExcludedContainer_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.B.: webm,ogg.
        /// </summary>
        public static string SettingsView_ExcludedContainer_Desc_2 {
            get {
                return ResourceManager.GetString("SettingsView_ExcludedContainer_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgeschlossene Formate.
        /// </summary>
        public static string SettingsView_ExcludedContainer_Text {
            get {
                return ResourceManager.GetString("SettingsView_ExcludedContainer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Vorlage wird zur Generierung des Dateinamen der Downloads benutzt.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mögliche Variablen:.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_2 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Position des Videos in einer Playlist (falls vorhanden).
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_3 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Videotitel.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_4 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Videoautor.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_5 {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $titel.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Desc_Var_title {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Desc_Var_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateinamenvorlage.
        /// </summary>
        public static string SettingsView_FileNameTemplate_Hint {
            get {
                return ResourceManager.GetString("SettingsView_FileNameTemplate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medien-Tags können automatisch aus dem Videotitel abgeleitet und in die gespeicherte Datei eingefügt werden.
        /// </summary>
        public static string SettingsView_InjectTags_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_InjectTags_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medien-Tags automatisch einbinden.
        /// </summary>
        public static string SettingsView_InjectTags_Text {
            get {
                return ResourceManager.GetString("SettingsView_InjectTags_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der gleichzeitig aktiven Downloads.
        /// </summary>
        public static string SettingsView_MaxDownloads_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_MaxDownloads_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel limit:.
        /// </summary>
        public static string SettingsView_MaxDownloads_Text {
            get {
                return ResourceManager.GetString("SettingsView_MaxDownloads_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei mehreren Videodownloads, werden gleichnaminge Datein in einem Ordner nicht erneut heruntergeladen.
        /// </summary>
        public static string SettingsView_SkipExistingFiles_Desc_1 {
            get {
                return ResourceManager.GetString("SettingsView_SkipExistingFiles_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorhandene Downloads überspringen.
        /// </summary>
        public static string SettingsView_SkipExistingFiles_Text {
            get {
                return ResourceManager.GetString("SettingsView_SkipExistingFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib die Lizenz zur Aktivierung  ein!.
        /// </summary>
        public static string TokenVerifyView_Desc_1 {
            get {
                return ResourceManager.GetString("TokenVerifyView_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Verbindung zur Datenbank hergestellt werden!.
        /// </summary>
        public static string TokenVerifyView_NoConnection_Ex {
            get {
                return ResourceManager.GetString("TokenVerifyView_NoConnection_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Internetverbindung hergestellt werden!.
        /// </summary>
        public static string TokenVerifyView_NoConnection_Internet {
            get {
                return ResourceManager.GetString("TokenVerifyView_NoConnection_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lizenz verifizieren.
        /// </summary>
        public static string TokenVerifyView_Title {
            get {
                return ResourceManager.GetString("TokenVerifyView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JETZT INSTALLIEREN.
        /// </summary>
        public static string Update_Button {
            get {
                return ResourceManager.GetString("Update_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update von % herunterladen....
        /// </summary>
        public static string Update_Desc_1 {
            get {
                return ResourceManager.GetString("Update_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Update wurde heruntergeladen und wird beim Beenden installiert.
        /// </summary>
        public static string Update_Desc_2 {
            get {
                return ResourceManager.GetString("Update_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Updaten des Downloaders.
        /// </summary>
        public static string Update_Error_Desc {
            get {
                return ResourceManager.GetString("Update_Error_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Verbindung zum Updateserver hergestellt werden..
        /// </summary>
        public static string UpdateService_No_Connection {
            get {
                return ResourceManager.GetString("UpdateService_No_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine passende Download-Option gefunden..
        /// </summary>
        public static string VideoDownloader_No_Download {
            get {
                return ResourceManager.GetString("VideoDownloader_No_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höchste.
        /// </summary>
        public static string VideoDownloader_Quality_Highest {
            get {
                return ResourceManager.GetString("VideoDownloader_Quality_Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niedrigste.
        /// </summary>
        public static string VideoDownloader_Quality_Lowest {
            get {
                return ResourceManager.GetString("VideoDownloader_Quality_Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ergebnisse.
        /// </summary>
        public static string VideoDownloader_Query_Count {
            get {
                return ResourceManager.GetString("VideoDownloader_Query_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannte bevorzugte Videoqualität.
        /// </summary>
        public static string VideoDownloader_Unkown_Quality {
            get {
                return ResourceManager.GetString("VideoDownloader_Unkown_Quality", resourceCulture);
            }
        }
    }
}
