name: CD

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  Build-Project:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1.x'

    - name: Build & publish
      run: dotnet publish YoutubeDownloader/ -o YoutubeDownloader/bin/Publish/ --configuration Release

    - name: Create installer
      run: |
        choco install innosetup --no-progress
        Copy-Item -Path YoutubeDownloader/bin/Publish/ -Recurse -Destination Installer/Source/
        & "c:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer/Installer.iss
      shell: pwsh

    - name: Create archive
      run: Compress-Archive -Path YoutubeDownloader/bin/Publish/* -DestinationPath YoutubeDownloader/bin/Publish/Archive.zip -Force
      shell: pwsh

    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          [Changelog](https://github.com/derech1e/YoutubeDownloader/blob/master/Changelog.md)
        draft: false
        prerelease: false

    - name: Upload release asset (archive)
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: YoutubeDownloader/bin/Publish/Archive.zip
        asset_name: YoutubeDownloader.zip
        asset_content_type: application/zip

    - name: Upload release asset (installer)
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Installer/bin/YoutubeDownloader-Installer.exe
        asset_name: YoutubeDownloader-Installer.exe
        asset_content_type: application/octet-stream