name: CI

on: [push, pull_request]

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month'
        skip-tags: true
        skip-recent: 3
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.100

    - name: Build & test
      run: dotnet test --configuration Release --logger GitHubActions

    - name: Build & publish
      run: dotnet publish YoutubeDownloader/ -o YoutubeDownloader/bin/Publish/ --configuration Release

    - name: Create installer
      run: |
        choco install innosetup --no-progress
        Copy-Item -Path YoutubeDownloader/bin/Publish/ -Recurse -Destination Installer/Source/
        & "c:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer/Installer.iss
      shell: pwsh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: YoutubeDownloader
        path: YoutubeDownloader/bin/Publish/

    - name: Upload build artifact (installer)
      uses: actions/upload-artifact@v1
      with:
        name: YoutubeDownloader-Installer
        path: Installer/bin/YoutubeDownloader-Installer.exe
