name: CI

on: [push, pull_request]

jobs:
  Remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '15 days'
        skip-tags: true
        skip-recent: 3
  Build-Project:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1.x'

    - name: Build & test
      run: dotnet test --configuration Release --logger GitHubActions

    - name: Build & publish
      run: dotnet publish YoutubeDownloader/ -o YoutubeDownloader/bin/Publish/ --configuration Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: YoutubeDownloader
        path: YoutubeDownloader/bin/Publish/
