name: CI

on: [push, pull_request]

jobs:
  Build-Project:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        # Fixed version, workaround for https://github.com/dotnet/core/issues/7176
        dotnet-version: 6.0.100
        
    - name: Build & publish
      run: dotnet publish YoutubeDownloader/ -o YoutubeDownloader/bin/Publish --configuration Release

    - name: Create installer
      run: |
        choco install innosetup
        Copy-Item -Path YoutubeDownloader/bin/Publish/ -Recurse -Destination Installer/Source/
        & "c:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer/Installer.iss
      shell: pwsh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: YoutubeDownloader
        path: YoutubeDownloader/bin/Publish/

    - name: Upload build artifact (installer)
      uses: actions/upload-artifact@v1
      with:
        name: YoutubeDownloader-Installer
        path: Installer/bin/YoutubeDownloader-Installer.exe
