name: CI

on: [push, pull_request]

jobs:
  Remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '5 days'
        skip-tags: false
        skip-recent: 2
  Build-Project:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1.x'

    - name: Build & publish
      run: dotnet publish YoutubeDownloader/ -o YoutubeDownloader/bin/Publish --configuration Release

    - name: Pack
      run: Compress-Archive -Path YoutubeDownloader/bin/Publish/* -DestinationPath YoutubeDownloader/bin/Publish/Archive.zip -Force
      shell: pwsh

    - name: Create installer
      run: |
        choco install innosetup --no-progress
        Copy-Item -Path YoutubeDownloader/bin/Publish/ -Recurse -Destination Installer/Source/
        & "c:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer/Installer.iss
      shell: pwsh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: YoutubeDownloader
        path: YoutubeDownloader/bin/Publish/

    - name: Upload build artifact (installer)
      uses: actions/upload-artifact@v1
      with:
        name: YoutubeDownloader-Installer
        path: Installer/bin/YoutubeDownloader-Installer.exe
